import type {
  CategoriaNotaFiscal,
  EtapaNotaFiscal,
} from "@/lib/nota-fiscal-constants";
import { expandirCatalogoObra } from "@/lib/nota-fiscal-catalogo-build";

export type EntradaCatalogoObra = {
  termo: string;
  categoria: CategoriaNotaFiscal;
  etapa: EtapaNotaFiscal;
  unidade?: string;
  sinonimos?: string[];
};

/** Entradas canônicas com unidade padrão e sinônimos estruturados. */
const CATALOGO_CANONICO: EntradaCatalogoObra[] = [
  {
    termo: "cimento",
    categoria: "Material",
    etapa: "Fundação",
    unidade: "SC",
    sinonimos: ["cimento cp ii", "cimento cp-ii", "cimento portland", "saco cimento"],
  },
  {
    termo: "argamassa",
    categoria: "Material",
    etapa: "Alvenaria",
    unidade: "SC",
    sinonimos: ["argamassa colante", "argamassa de assentamento"],
  },
  {
    termo: "areia",
    categoria: "Material",
    etapa: "Fundação",
    unidade: "M3",
    sinonimos: ["areia media", "areia média", "areia fina", "areia grossa"],
  },
  {
    termo: "brita",
    categoria: "Material",
    etapa: "Fundação",
    unidade: "M3",
    sinonimos: ["brita 0", "brita 1", "brita 2", "pedra britada"],
  },
  {
    termo: "bloco",
    categoria: "Material",
    etapa: "Alvenaria",
    unidade: "UN",
    sinonimos: ["bloco de concreto", "bloco ceramico", "bloco cerâmico"],
  },
  {
    termo: "tijolo",
    categoria: "Material",
    etapa: "Alvenaria",
    unidade: "UN",
    sinonimos: ["tijolo ceramico", "tijolo cerâmico", "tijolo macico"],
  },
  {
    termo: "aco ca50",
    categoria: "Material",
    etapa: "Superestrutura",
    unidade: "KG",
    sinonimos: ["aço ca50", "aco ca-50", "vergalhao", "vergalhão", "barra de aco"],
  },
  {
    termo: "prego",
    categoria: "Material",
    etapa: "Não classificado",
    unidade: "KG",
    sinonimos: ["prego de aco", "prego de aço"],
  },
  {
    termo: "parafuso",
    categoria: "Material",
    etapa: "Não classificado",
    unidade: "UN",
    sinonimos: ["parafuso sextavado", "parafuso allen"],
  },
  {
    termo: "tubo pvc",
    categoria: "Material",
    etapa: "Instalações hidráulicas",
    unidade: "UN",
    sinonimos: ["tubo pvc soldavel", "tubo pvc soldável", "tubo esgoto", "tubo agua"],
  },
  {
    termo: "conexao",
    categoria: "Material",
    etapa: "Instalações hidráulicas",
    unidade: "UN",
    sinonimos: ["conexão", "conexoes pvc", "joelho pvc", "te pvc", "luva pvc"],
  },
  {
    termo: "fio eletrico",
    categoria: "Material",
    etapa: "Instalações elétricas",
    unidade: "M",
    sinonimos: ["fio elétrico", "fio 2.5mm", "fio 2,5 mm", "fio 4mm", "cabo pp"],
  },
  {
    termo: "disjuntor",
    categoria: "Material",
    etapa: "Instalações elétricas",
    unidade: "UN",
    sinonimos: ["disjuntor monopolar", "disjuntor bipolar"],
  },
  {
    termo: "quadro eletrico",
    categoria: "Material",
    etapa: "Instalações elétricas",
    unidade: "UN",
    sinonimos: ["quadro elétrico", "quadro de distribuicao", "qd"],
  },
  {
    termo: "tinta",
    categoria: "Material",
    etapa: "Pintura",
    unidade: "GL",
    sinonimos: ["tinta latex", "tinta látex", "tinta acrilica", "tinta acrílica"],
  },
  {
    termo: "massa corrida",
    categoria: "Material",
    etapa: "Pintura",
    unidade: "KG",
    sinonimos: ["massa acrilica", "massa acrílica"],
  },
  {
    termo: "impermeabilizante",
    categoria: "Material",
    etapa: "Impermeabilização",
    unidade: "KG",
    sinonimos: ["manta asfaltica", "manta asfáltica", "sika"],
  },
  {
    termo: "porcelanato",
    categoria: "Material",
    etapa: "Pisos",
    unidade: "M2",
    sinonimos: ["piso porcelanato"],
  },
  {
    termo: "ceramica",
    categoria: "Material",
    etapa: "Revestimentos",
    unidade: "M2",
    sinonimos: ["cerâmica", "azulejo", "revestimento ceramico"],
  },
  {
    termo: "gesso",
    categoria: "Material",
    etapa: "Acabamento",
    unidade: "M2",
    sinonimos: ["gesso acartonado", "drywall", "placa de gesso"],
  },
  {
    termo: "madeira",
    categoria: "Material",
    etapa: "Cobertura",
    unidade: "M",
    sinonimos: ["caibro", "terca", "terça", "prancha", "tabua"],
  },
  {
    termo: "esquadria",
    categoria: "Material",
    etapa: "Esquadrias",
    unidade: "UN",
    sinonimos: ["esquadrias", "porta", "janela", "batente"],
  },
  {
    termo: "vidro",
    categoria: "Material",
    etapa: "Esquadrias",
    unidade: "M2",
    sinonimos: ["vidro temperado", "box blindex"],
  },
  {
    termo: "telha",
    categoria: "Material",
    etapa: "Cobertura",
    unidade: "UN",
    sinonimos: ["telha ceramica", "telha cerâmica", "telha fibrocimento"],
  },
  {
    termo: "manta",
    categoria: "Material",
    etapa: "Impermeabilização",
    unidade: "M2",
    sinonimos: ["manta termica", "manta térmica"],
  },
  {
    termo: "elevador",
    categoria: "Equipamento",
    etapa: "Acabamento",
    unidade: "UN",
    sinonimos: ["elevador residencial", "montagem elevador"],
  },
  {
    termo: "bomba",
    categoria: "Equipamento",
    etapa: "Instalações hidráulicas",
    unidade: "UN",
    sinonimos: ["bomba dagua", "bomba d'água", "bomba pressurizadora"],
  },
  {
    termo: "concreto usinado",
    categoria: "Material",
    etapa: "Fundação",
    unidade: "M3",
    sinonimos: ["concreto bombeado", "concreto fck"],
  },
  {
    termo: "aluguel de maquina",
    categoria: "Equipamento",
    etapa: "Não classificado",
    unidade: "UN",
    sinonimos: ["aluguel de máquina", "locacao de equipamento", "locação de equipamento"],
  },
  {
    termo: "frete",
    categoria: "Frete",
    etapa: "Não classificado",
    unidade: "UN",
    sinonimos: ["entrega", "transporte", "carreto"],
  },
  {
    termo: "pedreiro",
    categoria: "Mão de obra",
    etapa: "Não classificado",
    unidade: "UN",
    sinonimos: ["servente", "diaria pedreiro", "diária pedreiro", "mao de obra", "mão de obra"],
  },
  {
    termo: "servico terceirizado",
    categoria: "Serviço terceirizado",
    etapa: "Não classificado",
    unidade: "UN",
    sinonimos: ["serviço terceirizado", "terceirizado", "subempreiteiro"],
  },
];

/** Catálogo interno de materiais, ferramentas e serviços da construção civil. */
const CATALOGO_OBRA_BASE: EntradaCatalogoObra[] = [
  // ── Serviços preliminares ──
  { termo: "locacao", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },
  { termo: "locação", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },
  { termo: "topografia", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },
  { termo: "sondagem", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },
  { termo: "terraplanagem", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },
  { termo: "limpeza de terreno", categoria: "Mão de obra", etapa: "Serviços preliminares" },
  { termo: "tapume", categoria: "Material", etapa: "Serviços preliminares" },
  { termo: "placa de obra", categoria: "Material", etapa: "Serviços preliminares" },
  { termo: "container", categoria: "Equipamento", etapa: "Serviços preliminares" },
  { termo: "cercamento", categoria: "Material", etapa: "Serviços preliminares" },
  { termo: "telas de obra", categoria: "Material", etapa: "Serviços preliminares" },
  { termo: "placa indicativa", categoria: "Material", etapa: "Serviços preliminares" },
  { termo: "demolicao", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },
  { termo: "demolição", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },
  { termo: "retirada de entulho", categoria: "Serviço terceirizado", etapa: "Serviços preliminares" },

  // ── Fundação ──
  { termo: "cimento", categoria: "Material", etapa: "Fundação" },
  { termo: "cimento cp ii", categoria: "Material", etapa: "Fundação" },
  { termo: "cimento cp-ii", categoria: "Material", etapa: "Fundação" },
  { termo: "cimento cp iv", categoria: "Material", etapa: "Fundação" },
  { termo: "cimento cp-iv", categoria: "Material", etapa: "Fundação" },
  { termo: "cimento cp v", categoria: "Material", etapa: "Fundação" },
  { termo: "areia media", categoria: "Material", etapa: "Fundação" },
  { termo: "areia média", categoria: "Material", etapa: "Fundação" },
  { termo: "areia fina", categoria: "Material", etapa: "Fundação" },
  { termo: "areia grossa", categoria: "Material", etapa: "Fundação" },
  { termo: "brita 0", categoria: "Material", etapa: "Fundação" },
  { termo: "brita 1", categoria: "Material", etapa: "Fundação" },
  { termo: "brita 2", categoria: "Material", etapa: "Fundação" },
  { termo: "brita 3", categoria: "Material", etapa: "Fundação" },
  { termo: "pedra britada", categoria: "Material", etapa: "Fundação" },
  { termo: "concreto usinado", categoria: "Material", etapa: "Fundação" },
  { termo: "concreto magro", categoria: "Material", etapa: "Fundação" },
  { termo: "concreto fck", categoria: "Material", etapa: "Fundação" },
  { termo: "sapata", categoria: "Material", etapa: "Fundação" },
  { termo: "sapata isolada", categoria: "Material", etapa: "Fundação" },
  { termo: "bloco de coroamento", categoria: "Material", etapa: "Fundação" },
  { termo: "viga baldrame", categoria: "Material", etapa: "Fundação" },
  { termo: "baldrame", categoria: "Material", etapa: "Fundação" },
  { termo: "estaca", categoria: "Material", etapa: "Fundação" },
  { termo: "estaca raiz", categoria: "Material", etapa: "Fundação" },
  { termo: "tubulao", categoria: "Material", etapa: "Fundação" },
  { termo: "tubulão", categoria: "Material", etapa: "Fundação" },
  { termo: "radier", categoria: "Material", etapa: "Fundação" },
  { termo: "radier", categoria: "Material", etapa: "Fundação" },
  { termo: "formao", categoria: "Material", etapa: "Fundação" },
  { termo: "formão", categoria: "Material", etapa: "Fundação" },
  { termo: "desmoldante", categoria: "Material", etapa: "Fundação" },
  { termo: "aditivo plastificante", categoria: "Material", etapa: "Fundação" },
  { termo: "impermeabilizante de concreto", categoria: "Material", etapa: "Fundação" },
  { termo: "tela pop", categoria: "Material", etapa: "Fundação" },
  { termo: "tela de polietileno", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhao 6.3", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhão 6.3", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhao 8.0", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhão 8.0", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhao 10", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhão 10", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhao 12.5", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhão 12.5", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhao 16", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhão 16", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhao 20", categoria: "Material", etapa: "Fundação" },
  { termo: "vergalhão 20", categoria: "Material", etapa: "Fundação" },
  { termo: "armadura", categoria: "Material", etapa: "Fundação" },
  { termo: "ferro CA-50", categoria: "Material", etapa: "Fundação" },
  { termo: "ferro ca-50", categoria: "Material", etapa: "Fundação" },
  { termo: "ferro CA-60", categoria: "Material", etapa: "Fundação" },
  { termo: "arame recozido", categoria: "Material", etapa: "Fundação" },
  { termo: "escoramento", categoria: "Material", etapa: "Fundação" },
  { termo: "escora metalica", categoria: "Material", etapa: "Fundação" },
  { termo: "escora metálica", categoria: "Material", etapa: "Fundação" },
  { termo: "compactedora", categoria: "Equipamento", etapa: "Fundação" },
  { termo: "compactador", categoria: "Equipamento", etapa: "Fundação" },

  // ── Infraestrutura ──
  { termo: "drenagem", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "grelha", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "boca de lobo", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "caixa de inspecao", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "caixa de inspeção", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "tubo de concreto", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "manilha", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "fossa septica", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "fossa séptica", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "sumidouro", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "rede pluvial", categoria: "Material", etapa: "Infraestrutura" },
  { termo: "rede de esgoto", categoria: "Material", etapa: "Infraestrutura" },

  // ── Superestrutura ──
  { termo: "pilar", categoria: "Material", etapa: "Superestrutura" },
  { termo: "viga", categoria: "Material", etapa: "Superestrutura" },
  { termo: "laje", categoria: "Material", etapa: "Superestrutura" },
  { termo: "laje pre-moldada", categoria: "Material", etapa: "Superestrutura" },
  { termo: "laje pré-moldada", categoria: "Material", etapa: "Superestrutura" },
  { termo: "laje nervurada", categoria: "Material", etapa: "Superestrutura" },
  { termo: "lajota", categoria: "Material", etapa: "Superestrutura" },
  { termo: "tavela", categoria: "Material", etapa: "Superestrutura" },
  { termo: "tábua", categoria: "Material", etapa: "Superestrutura" },
  { termo: "tabua", categoria: "Material", etapa: "Superestrutura" },
  { termo: "compensado", categoria: "Material", etapa: "Superestrutura" },
  { termo: "compensado naval", categoria: "Material", etapa: "Superestrutura" },
  { termo: "concreto estrutural", categoria: "Material", etapa: "Superestrutura" },
  { termo: "fôrma", categoria: "Material", etapa: "Superestrutura" },
  { termo: "forma", categoria: "Material", etapa: "Superestrutura" },
  { termo: "pranchao", categoria: "Material", etapa: "Superestrutura" },
  { termo: "pranchão", categoria: "Material", etapa: "Superestrutura" },
  { termo: "sarrafao", categoria: "Material", etapa: "Superestrutura" },
  { termo: "sarrafão", categoria: "Material", etapa: "Superestrutura" },
  { termo: "caibro", categoria: "Material", etapa: "Superestrutura" },
  { termo: "pontalete", categoria: "Material", etapa: "Superestrutura" },
  { termo: "viga de madeira", categoria: "Material", etapa: "Superestrutura" },
  { termo: "concreto armado", categoria: "Material", etapa: "Superestrutura" },
  { termo: "vergalhao 25", categoria: "Material", etapa: "Superestrutura" },
  { termo: "vergalhão 25", categoria: "Material", etapa: "Superestrutura" },
  { termo: "vergalhao 32", categoria: "Material", etapa: "Superestrutura" },
  { termo: "vergalhão 32", categoria: "Material", etapa: "Superestrutura" },
  { termo: "trelica", categoria: "Material", etapa: "Superestrutura" },
  { termo: "treliça", categoria: "Material", etapa: "Superestrutura" },
  { termo: "eps", categoria: "Material", etapa: "Superestrutura" },
  { termo: "isopor laje", categoria: "Material", etapa: "Superestrutura" },
  { termo: "bloco de eps", categoria: "Material", etapa: "Superestrutura" },

  // ── Alvenaria ──
  { termo: "tijolo", categoria: "Material", etapa: "Alvenaria" },
  { termo: "tijolo ceramico", categoria: "Material", etapa: "Alvenaria" },
  { termo: "tijolo cerâmico", categoria: "Material", etapa: "Alvenaria" },
  { termo: "tijolo macico", categoria: "Material", etapa: "Alvenaria" },
  { termo: "tijolo maciço", categoria: "Material", etapa: "Alvenaria" },
  { termo: "tijolo furado", categoria: "Material", etapa: "Alvenaria" },
  { termo: "bloco ceramico", categoria: "Material", etapa: "Alvenaria" },
  { termo: "bloco cerâmico", categoria: "Material", etapa: "Alvenaria" },
  { termo: "bloco de concreto", categoria: "Material", etapa: "Alvenaria" },
  { termo: "bloco estrutural", categoria: "Material", etapa: "Alvenaria" },
  { termo: "bloco de vedacao", categoria: "Material", etapa: "Alvenaria" },
  { termo: "bloco de vedação", categoria: "Material", etapa: "Alvenaria" },
  { termo: "argamassa de assentamento", categoria: "Material", etapa: "Alvenaria" },
  { termo: "argamassa colante", categoria: "Material", etapa: "Alvenaria" },
  { termo: "cal hidratada", categoria: "Material", etapa: "Alvenaria" },
  { termo: "cal", categoria: "Material", etapa: "Alvenaria" },
  { termo: "gesso", categoria: "Material", etapa: "Alvenaria" },
  { termo: "gesso acartonado", categoria: "Material", etapa: "Alvenaria" },
  { termo: "drywall", categoria: "Material", etapa: "Alvenaria" },
  { termo: "placa de gesso", categoria: "Material", etapa: "Alvenaria" },
  { termo: "perfil de gesso", categoria: "Material", etapa: "Alvenaria" },
  { termo: "montante", categoria: "Material", etapa: "Alvenaria" },
  { termo: "guia de gesso", categoria: "Material", etapa: "Alvenaria" },
  { termo: "lintel", categoria: "Material", etapa: "Alvenaria" },
  { termo: "verga", categoria: "Material", etapa: "Alvenaria" },
  { termo: "contraverga", categoria: "Material", etapa: "Alvenaria" },
  { termo: "cinta", categoria: "Material", etapa: "Alvenaria" },
  { termo: "amarracao", categoria: "Material", etapa: "Alvenaria" },
  { termo: "amarração", categoria: "Material", etapa: "Alvenaria" },

  // ── Cobertura ──
  { termo: "telha", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha ceramica", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha cerâmica", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha de concreto", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha fibrocimento", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha fibro cimento", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha metalica", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha metálica", categoria: "Material", etapa: "Cobertura" },
  { termo: "telha zipada", categoria: "Material", etapa: "Cobertura" },
  { termo: "cumeeira", categoria: "Material", etapa: "Cobertura" },
  { termo: "rufo", categoria: "Material", etapa: "Cobertura" },
  { termo: "calha", categoria: "Material", etapa: "Cobertura" },
  { termo: "calha galvanizada", categoria: "Material", etapa: "Cobertura" },
  { termo: "terracota", categoria: "Material", etapa: "Cobertura" },
  { termo: "madeira telhado", categoria: "Material", etapa: "Cobertura" },
  { termo: "terca", categoria: "Material", etapa: "Cobertura" },
  { termo: "terça", categoria: "Material", etapa: "Cobertura" },
  { termo: "ripa", categoria: "Material", etapa: "Cobertura" },
  { termo: "manta termica", categoria: "Material", etapa: "Cobertura" },
  { termo: "manta térmica", categoria: "Material", etapa: "Cobertura" },
  { termo: "manta aluminizada", categoria: "Material", etapa: "Cobertura" },
  { termo: "estrutura de telhado", categoria: "Material", etapa: "Cobertura" },
  { termo: "parafuso telha", categoria: "Material", etapa: "Cobertura" },

  // ── Instalações elétricas ──
  { termo: "fio", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "fio eletrico", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "fio elétrico", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "cabo eletrico", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "cabo elétrico", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "cabo flexivel", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "cabo flexível", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "disjuntor", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "dr", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "dps", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "quadro eletrico", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "quadro elétrico", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "quadro de distribuicao", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "tomada", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "interruptor", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "eletroduto", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "eletrocalha", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "conduite", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "curva eletroduto", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "luminaria", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "luminária", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "lampada", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "lâmpada", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "led", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "spot", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "fita led", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "caixa de passagem", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "haste aterramento", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "aterramento", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "fio terra", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "barra din", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "sensor presenca", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "sensor presença", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "ventilador teto", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "ventilador de teto", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "cabo de rede", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "cabo coaxial", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "regua de tomada", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "régua de tomada", categoria: "Material", etapa: "Instalações elétricas" },

  // ── Instalações hidráulicas ──
  { termo: "tubo pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tubo PVC", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tubo esgoto", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tubo agua", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tubo água", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tubo ppr", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tubo PPR", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tubo cobre", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "conexao pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "conexão pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "joelho pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "te pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "luva pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "registro", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "registro gaveta", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "torneira", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "misturador", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "monocomando", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "caixa dagua", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "caixa d'agua", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "caixa d'água", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "boia caixa dagua", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "bomba d'agua", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "bomba d'água", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "bomba pressurizadora", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "vaso sanitario", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "vaso sanitário", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "bacia sanitária", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "bacia sanitaria", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "caixa acoplada", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "pia", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "cuba", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "tanque", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "ralo", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "sifao", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "sifão", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "chuveiro", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "ducha", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "ducha higienica", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "ducha higiênica", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "valvula descarga", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "válvula descarga", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "cola pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "solda pvc", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "filtro de agua", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "filtro de água", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "aquecedor", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "aquecedor solar", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "hidrometro", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "hidrômetro", categoria: "Material", etapa: "Instalações hidráulicas" },

  // ── Impermeabilização ──
  { termo: "manta asfaltica", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "manta asfáltica", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "manta aluminio", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "manta alumínio", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "impermeabilizante", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "sika", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "védacit", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "vedacit", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "selante pu", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "selante pu", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "membrana", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "primer impermeabilizante", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "tinta impermeabilizante", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "argamassa polimerica", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "argamassa polimérica", categoria: "Material", etapa: "Impermeabilização" },

  // ── Revestimentos ──
  { termo: "revestimento ceramico", categoria: "Material", etapa: "Revestimentos" },
  { termo: "revestimento cerâmico", categoria: "Material", etapa: "Revestimentos" },
  { termo: "azulejo", categoria: "Material", etapa: "Revestimentos" },
  { termo: "pastilha", categoria: "Material", etapa: "Revestimentos" },
  { termo: "filete", categoria: "Material", etapa: "Revestimentos" },
  { termo: "porcelanato parede", categoria: "Material", etapa: "Revestimentos" },
  { termo: "revestimento 3d", categoria: "Material", etapa: "Revestimentos" },
  { termo: "revestimento 3D", categoria: "Material", etapa: "Revestimentos" },
  { termo: "argamassa AC-II", categoria: "Material", etapa: "Revestimentos" },
  { termo: "argamassa ac-ii", categoria: "Material", etapa: "Revestimentos" },
  { termo: "argamassa AC-III", categoria: "Material", etapa: "Revestimentos" },
  { termo: "nivelador piso", categoria: "Material", etapa: "Revestimentos" },
  { termo: "nivelador de piso", categoria: "Material", etapa: "Revestimentos" },
  { termo: "cunha niveladora", categoria: "Material", etapa: "Revestimentos" },
  { termo: "espacador", categoria: "Material", etapa: "Revestimentos" },
  { termo: "espaçador", categoria: "Material", etapa: "Revestimentos" },
  { termo: "rodape", categoria: "Material", etapa: "Revestimentos" },
  { termo: "rodapé", categoria: "Material", etapa: "Revestimentos" },
  { termo: "soleira", categoria: "Material", etapa: "Revestimentos" },
  { termo: "peitoril", categoria: "Material", etapa: "Revestimentos" },

  // ── Pisos ──
  { termo: "porcelanato", categoria: "Material", etapa: "Pisos" },
  { termo: "ceramica piso", categoria: "Material", etapa: "Pisos" },
  { termo: "cerâmica piso", categoria: "Material", etapa: "Pisos" },
  { termo: "piso ceramico", categoria: "Material", etapa: "Pisos" },
  { termo: "piso cerâmico", categoria: "Material", etapa: "Pisos" },
  { termo: "piso vinilico", categoria: "Material", etapa: "Pisos" },
  { termo: "piso vinílico", categoria: "Material", etapa: "Pisos" },
  { termo: "piso laminado", categoria: "Material", etapa: "Pisos" },
  { termo: "piso de madeira", categoria: "Material", etapa: "Pisos" },
  { termo: "deck", categoria: "Material", etapa: "Pisos" },
  { termo: "granito", categoria: "Material", etapa: "Pisos" },
  { termo: "marmore", categoria: "Material", etapa: "Pisos" },
  { termo: "mármore", categoria: "Material", etapa: "Pisos" },
  { termo: "cimento queimado", categoria: "Material", etapa: "Pisos" },
  { termo: "contrapiso", categoria: "Material", etapa: "Pisos" },
  { termo: "autonivelante", categoria: "Material", etapa: "Pisos" },
  { termo: "autonivelante", categoria: "Material", etapa: "Pisos" },
  { termo: "manta acustica", categoria: "Material", etapa: "Pisos" },
  { termo: "manta acústica", categoria: "Material", etapa: "Pisos" },

  // ── Esquadrias ──
  { termo: "porta", categoria: "Material", etapa: "Esquadrias" },
  { termo: "porta de madeira", categoria: "Material", etapa: "Esquadrias" },
  { termo: "porta de aluminio", categoria: "Material", etapa: "Esquadrias" },
  { termo: "porta de alumínio", categoria: "Material", etapa: "Esquadrias" },
  { termo: "porta de aco", categoria: "Material", etapa: "Esquadrias" },
  { termo: "porta de aço", categoria: "Material", etapa: "Esquadrias" },
  { termo: "janela", categoria: "Material", etapa: "Esquadrias" },
  { termo: "janela de aluminio", categoria: "Material", etapa: "Esquadrias" },
  { termo: "janela de alumínio", categoria: "Material", etapa: "Esquadrias" },
  { termo: "janela de pvc", categoria: "Material", etapa: "Esquadrias" },
  { termo: "janela de PVC", categoria: "Material", etapa: "Esquadrias" },
  { termo: "vidro", categoria: "Material", etapa: "Esquadrias" },
  { termo: "vidro temperado", categoria: "Material", etapa: "Esquadrias" },
  { termo: "box blindex", categoria: "Material", etapa: "Esquadrias" },
  { termo: "box de banheiro", categoria: "Material", etapa: "Esquadrias" },
  { termo: "fechadura", categoria: "Material", etapa: "Esquadrias" },
  { termo: "dobradica", categoria: "Material", etapa: "Esquadrias" },
  { termo: "dobradiça", categoria: "Material", etapa: "Esquadrias" },
  { termo: "macanet", categoria: "Material", etapa: "Esquadrias" },
  { termo: "maçanet", categoria: "Material", etapa: "Esquadrias" },
  { termo: "maçaneta", categoria: "Material", etapa: "Esquadrias" },
  { termo: "portao", categoria: "Material", etapa: "Esquadrias" },
  { termo: "portão", categoria: "Material", etapa: "Esquadrias" },
  { termo: "persiana", categoria: "Material", etapa: "Esquadrias" },
  { termo: "cortina de vidro", categoria: "Material", etapa: "Esquadrias" },
  { termo: "guilhotina", categoria: "Material", etapa: "Esquadrias" },

  // ── Pintura ──
  { termo: "tinta", categoria: "Material", etapa: "Pintura" },
  { termo: "tinta latex", categoria: "Material", etapa: "Pintura" },
  { termo: "tinta látex", categoria: "Material", etapa: "Pintura" },
  { termo: "tinta acrilica", categoria: "Material", etapa: "Pintura" },
  { termo: "tinta acrílica", categoria: "Material", etapa: "Pintura" },
  { termo: "tinta esmalte", categoria: "Material", etapa: "Pintura" },
  { termo: "tinta piso", categoria: "Material", etapa: "Pintura" },
  { termo: "massa corrida", categoria: "Material", etapa: "Pintura" },
  { termo: "selador", categoria: "Material", etapa: "Pintura" },
  { termo: "selador acrilico", categoria: "Material", etapa: "Pintura" },
  { termo: "selador acrílico", categoria: "Material", etapa: "Pintura" },
  { termo: "tinner", categoria: "Material", etapa: "Pintura" },
  { termo: "thinner", categoria: "Material", etapa: "Pintura" },
  { termo: "rolo de pintura", categoria: "Material", etapa: "Pintura" },
  { termo: "pincel", categoria: "Material", etapa: "Pintura" },
  { termo: "trincha", categoria: "Material", etapa: "Pintura" },
  { termo: "lixa", categoria: "Material", etapa: "Pintura" },
  { termo: "fita crepe", categoria: "Material", etapa: "Pintura" },
  { termo: "textura", categoria: "Material", etapa: "Pintura" },
  { termo: "massa acrilica", categoria: "Material", etapa: "Pintura" },
  { termo: "massa acrílica", categoria: "Material", etapa: "Pintura" },
  { termo: "verniz", categoria: "Material", etapa: "Pintura" },
  { termo: "stain", categoria: "Material", etapa: "Pintura" },

  // ── Acabamento ──
  { termo: "bancada", categoria: "Material", etapa: "Acabamento" },
  { termo: "bancada granito", categoria: "Material", etapa: "Acabamento" },
  { termo: "nicho", categoria: "Material", etapa: "Acabamento" },
  { termo: "espelho", categoria: "Material", etapa: "Acabamento" },
  { termo: "armario", categoria: "Material", etapa: "Acabamento" },
  { termo: "armário", categoria: "Material", etapa: "Acabamento" },
  { termo: "gabinete", categoria: "Material", etapa: "Acabamento" },
  { termo: "puxador", categoria: "Material", etapa: "Acabamento" },
  { termo: "corrimao", categoria: "Material", etapa: "Acabamento" },
  { termo: "corrimão", categoria: "Material", etapa: "Acabamento" },
  { termo: "guarda corpo", categoria: "Material", etapa: "Acabamento" },
  { termo: "guarda-corpo", categoria: "Material", etapa: "Acabamento" },
  { termo: "sancas", categoria: "Material", etapa: "Acabamento" },
  { termo: "sanca", categoria: "Material", etapa: "Acabamento" },
  { termo: "moldura", categoria: "Material", etapa: "Acabamento" },
  { termo: "rodape acabamento", categoria: "Material", etapa: "Acabamento" },
  { termo: "soleira acabamento", categoria: "Material", etapa: "Acabamento" },

  // ── Área externa ──
  { termo: "paver", categoria: "Material", etapa: "Área externa" },
  { termo: "bloquete", categoria: "Material", etapa: "Área externa" },
  { termo: "intertravado", categoria: "Material", etapa: "Área externa" },
  { termo: "piso intertravado", categoria: "Material", etapa: "Área externa" },
  { termo: "grama", categoria: "Material", etapa: "Área externa" },
  { termo: "jardim", categoria: "Material", etapa: "Área externa" },
  { termo: "cerca", categoria: "Material", etapa: "Área externa" },
  { termo: "gradil", categoria: "Material", etapa: "Área externa" },
  { termo: "piscina", categoria: "Material", etapa: "Área externa" },
  { termo: "deck area externa", categoria: "Material", etapa: "Área externa" },
  { termo: "pergolado", categoria: "Material", etapa: "Área externa" },
  { termo: "pergolado", categoria: "Material", etapa: "Área externa" },
  { termo: "paisagismo", categoria: "Serviço terceirizado", etapa: "Área externa" },
  { termo: "meio fio", categoria: "Material", etapa: "Área externa" },
  { termo: "meio-fio", categoria: "Material", etapa: "Área externa" },

  // ── Mão de obra ──
  { termo: "pedreiro", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "servente", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "eletricista", categoria: "Mão de obra", etapa: "Instalações elétricas" },
  { termo: "encanador", categoria: "Mão de obra", etapa: "Instalações hidráulicas" },
  { termo: "pintor", categoria: "Mão de obra", etapa: "Pintura" },
  { termo: "gesseiro", categoria: "Mão de obra", etapa: "Alvenaria" },
  { termo: "carpinteiro", categoria: "Mão de obra", etapa: "Superestrutura" },
  { termo: "armador", categoria: "Mão de obra", etapa: "Superestrutura" },
  { termo: "serralheiro", categoria: "Mão de obra", etapa: "Esquadrias" },
  { termo: "diaria", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "diária", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "quinzena", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "mao de obra", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "mão de obra", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "ajudante", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "profissional", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "equipe", categoria: "Mão de obra", etapa: "Não classificado" },
  { termo: "instalacao eletrica", categoria: "Mão de obra", etapa: "Instalações elétricas" },
  { termo: "instalação elétrica", categoria: "Mão de obra", etapa: "Instalações elétricas" },
  { termo: "instalacao hidraulica", categoria: "Mão de obra", etapa: "Instalações hidráulicas" },
  { termo: "instalação hidráulica", categoria: "Mão de obra", etapa: "Instalações hidráulicas" },

  // ── Equipamentos ──
  { termo: "betoneira", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "escavadeira", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "retroescavadeira", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "bobcat", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "guindaste", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "guincho", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "andaime", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "aluguel de maquina", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "aluguel de máquina", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "locacao de equipamento", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "locação de equipamento", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "martelete", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "martelete", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "furadeira", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "parafusadeira", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "serra circular", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "serra marmore", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "serra mármore", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "cortadora piso", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "nivel a laser", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "nivel laser", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "compressor", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "gerador", categoria: "Equipamento", etapa: "Não classificado" },
  { termo: "grupo gerador", categoria: "Equipamento", etapa: "Não classificado" },

  // ── Ferramentas (Material genérico ou Equipamento) ──
  { termo: "enxada", categoria: "Material", etapa: "Não classificado" },
  { termo: "pa", categoria: "Material", etapa: "Não classificado" },
  { termo: "pá", categoria: "Material", etapa: "Não classificado" },
  { termo: "carrinho de mao", categoria: "Material", etapa: "Não classificado" },
  { termo: "carrinho de mão", categoria: "Material", etapa: "Não classificado" },
  { termo: "balde", categoria: "Material", etapa: "Não classificado" },
  { termo: "colher de pedreiro", categoria: "Material", etapa: "Não classificado" },
  { termo: "desempenadeira", categoria: "Material", etapa: "Não classificado" },
  { termo: "espatula", categoria: "Material", etapa: "Não classificado" },
  { termo: "espátula", categoria: "Material", etapa: "Não classificado" },
  { termo: "trena", categoria: "Material", etapa: "Não classificado" },
  { termo: "metro", categoria: "Material", etapa: "Não classificado" },
  { termo: "nivel", categoria: "Material", etapa: "Não classificado" },
  { termo: "nível", categoria: "Material", etapa: "Não classificado" },
  { termo: "prumo", categoria: "Material", etapa: "Não classificado" },
  { termo: "linha de pedreiro", categoria: "Material", etapa: "Não classificado" },
  { termo: "martelo", categoria: "Material", etapa: "Não classificado" },
  { termo: "marreta", categoria: "Material", etapa: "Não classificado" },
  { termo: "talhadeira", categoria: "Material", etapa: "Não classificado" },
  { termo: "serra", categoria: "Material", etapa: "Não classificado" },
  { termo: "broca", categoria: "Material", etapa: "Não classificado" },
  { termo: "disco de corte", categoria: "Material", etapa: "Não classificado" },
  { termo: "luva", categoria: "Material", etapa: "Não classificado" },
  { termo: "capacete", categoria: "Material", etapa: "Não classificado" },
  { termo: "oculos de protecao", categoria: "Material", etapa: "Não classificado" },
  { termo: "óculos de proteção", categoria: "Material", etapa: "Não classificado" },
  { termo: "bota", categoria: "Material", etapa: "Não classificado" },
  { termo: "EPI", categoria: "Material", etapa: "Não classificado" },
  { termo: "epi", categoria: "Material", etapa: "Não classificado" },

  // ── Frete ──
  { termo: "frete", categoria: "Frete", etapa: "Não classificado" },
  { termo: "entrega", categoria: "Frete", etapa: "Não classificado" },
  { termo: "transporte", categoria: "Frete", etapa: "Não classificado" },
  { termo: "carreto", categoria: "Frete", etapa: "Não classificado" },
  { termo: "motoboy", categoria: "Frete", etapa: "Não classificado" },
  { termo: "carga", categoria: "Frete", etapa: "Não classificado" },

  // ── Serviços terceirizados ──
  { termo: "servico terceirizado", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "serviço terceirizado", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "terceirizado", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "subempreiteiro", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "subempreitada", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "montagem", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "manutencao", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "manutenção", categoria: "Serviço terceirizado", etapa: "Não classificado" },
  { termo: "limpeza pos obra", categoria: "Serviço terceirizado", etapa: "Acabamento" },
  { termo: "limpeza pós obra", categoria: "Serviço terceirizado", etapa: "Acabamento" },
  { termo: "limpeza final", categoria: "Serviço terceirizado", etapa: "Acabamento" },

  // ── Projeto e documentação ──
  { termo: "projeto arquitetonico", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "projeto arquitetônico", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "projeto estrutural", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "projeto hidraulico", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "projeto hidráulico", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "projeto eletrico", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "projeto elétrico", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "ART", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "art", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "RRt", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "rrt", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "laudo", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "memorial descritivo", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },
  { termo: "planta baixa", categoria: "Projeto e documentação", etapa: "Serviços preliminares" },

  // ── Impostos e taxas ──
  { termo: "ISS", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "iss", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "ICMS", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "icms", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "IPI", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "ipi", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "PIS", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "COFINS", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "taxa", categoria: "Impostos e taxas", etapa: "Não classificado" },
  { termo: "alvara", categoria: "Impostos e taxas", etapa: "Serviços preliminares" },
  { termo: "alvará", categoria: "Impostos e taxas", etapa: "Serviços preliminares" },
  { termo: "habite-se", categoria: "Impostos e taxas", etapa: "Acabamento" },
  { termo: "habite se", categoria: "Impostos e taxas", etapa: "Acabamento" },

  // ── Fixações e consumíveis gerais ──
  { termo: "parafuso", categoria: "Material", etapa: "Não classificado" },
  { termo: "bucha", categoria: "Material", etapa: "Não classificado" },
  { termo: "prego", categoria: "Material", etapa: "Não classificado" },
  { termo: "arame", categoria: "Material", etapa: "Não classificado" },
  { termo: "cola", categoria: "Material", etapa: "Não classificado" },
  { termo: "silicone", categoria: "Material", etapa: "Não classificado" },
  { termo: "fita veda rosca", categoria: "Material", etapa: "Instalações hidráulicas" },
  { termo: "fita isolante", categoria: "Material", etapa: "Instalações elétricas" },
  { termo: "abracadeira", categoria: "Material", etapa: "Não classificado" },
  { termo: "abraçadeira", categoria: "Material", etapa: "Não classificado" },
  { termo: "disco diamantado", categoria: "Material", etapa: "Pisos" },
  { termo: "rejunta", categoria: "Material", etapa: "Revestimentos" },
  { termo: "argamassa de rejuntamento", categoria: "Material", etapa: "Revestimentos" },
  { termo: "plastificante", categoria: "Material", etapa: "Fundação" },
  { termo: "impermeabilizante de juntas", categoria: "Material", etapa: "Impermeabilização" },
  { termo: "chapa de aco", categoria: "Material", etapa: "Superestrutura" },
  { termo: "chapa de aço", categoria: "Material", etapa: "Superestrutura" },
  { termo: "perfil metalico", categoria: "Material", etapa: "Superestrutura" },
  { termo: "perfil metálico", categoria: "Material", etapa: "Superestrutura" },
  { termo: "metalon", categoria: "Material", etapa: "Superestrutura" },
  { termo: "cantoneira", categoria: "Material", etapa: "Superestrutura" },
  { termo: "tela soldada", categoria: "Material", etapa: "Fundação" },
  { termo: "malha pop", categoria: "Material", etapa: "Fundação" },
  { termo: "espuma expansiva", categoria: "Material", etapa: "Esquadrias" },
  { termo: "poliuretano", categoria: "Material", etapa: "Esquadrias" },
  { termo: "lona plastica", categoria: "Material", etapa: "Serviços preliminares" },
  { termo: "lona plástica", categoria: "Material", etapa: "Serviços preliminares" },
  { termo: "saco de rafia", categoria: "Material", etapa: "Não classificado" },
  { termo: "big bag", categoria: "Material", etapa: "Não classificado" },
];

export const CATALOGO_OBRA = expandirCatalogoObra([
  ...CATALOGO_CANONICO,
  ...CATALOGO_OBRA_BASE,
]);

export const TOTAL_ENTRADAS_CATALOGO = CATALOGO_OBRA.length;
